version: 2.1
timezone:
  America/Los_Angeles

executors:
  chef-workstation:
    docker:
      - image: chef/chefworkstation:21.7.545

commands:
  setup_reports:
    description: Install Gems for Orchestrator
    steps:
      - run:
          name: Create Reports Directory
          command: mkdir reports
      - store_test_results:
          path: reports/

  install_orchestrator_gems:
    description: Install Gems for Orchestrator
    steps:
      - run:
          name: Install Gem colorize
          command: chef gem install colorize -v 0.8.1 --no-user-install --no-document
      - run:
          name: Install Gem deep_merge
          command: chef gem install deep_merge -v 1.2.1 --no-user-install --no-document
      - run:
          name: Install Gem rubocop-rake
          command: chef gem install rubocop-rake -v 0.6.0 --no-user-install --no-document

jobs:
  style_tests:
    executor: chef-workstation
    environment:
      GEM_HOME: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems
      GEM_PATH: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0
      GEM_ROOT: /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0
      CHEF_LICENSE: accept
    working_directory: ~/circulate
    steps:
      - checkout
      - install_orchestrator_gems
      - run:
          name: Run Rubocop
          command: /opt/chef-workstation/embedded/bin/rake test:style:ruby --trace

workflows:
  version: 2.1
  # Only have one job because not paying for parallel jobs (may have 4 with free now)
  style_tests:
    jobs:
      - style_tests:
          context: bonusbits_orchestrator
